export const wordSearchData = {
  grid: [
    ['J', 'A', 'V', 'A', 'S', 'C', 'R', 'I', 'P', 'T'],
    ['A', ' ', ' ', 'D', 'P', ' ', 'H', 'Y', ' ', 'R'],
    ['V', ' ', 'S', 'A', 'O', 'Y', ' ', 'T', 'E', ' '],
    ['A', 'S', 'R', 'E', 'A', 'C', 'T', 'K', 'M', 'H'],
    ['C', 'Q', 'C', 'M', 'M', ' ', 'C', 'H', ' ', 'L'],
    ['R', 'L', 'G', 'O', 'T', 'O', 'S', 'T', 'O', 'I'],
    ['G', 'I', 'T', 'T', 'D', 'N', 'S', 'M', 'R', 'N'],
    ['F', 'F', 'U', 'R', 'M', 'E', 'U', 'C', ' ', 'U'],
    ['C', 'F', 'R', 'R', 'Z', 'L', 'C', 'X', ' ', 'X'],
  ],
  /*List the left-most row and column number for each word. 
  The colour is the stripe used in the background for each word and the number is to arrange them based on layer order. 
  */
  clues: {
    across: [
      {
        number: 1,
        clue: 'JavaScript',
        row: 0,
        col: 0,
        answer: 'JavaScript',
        colour: 'bg-yellow-300 text-black',
      },
      {
        number: 2,
        clue: 'C',
        row: 7,
        col: 7,
        answer: 'C',
        colour: 'bg-purple-300 text-black',
      },
      {
        number: 3,
        clue: 'React',
        row: 3,
        col: 2,
        answer: 'React',
        colour: 'bg-green-300 text-black',
      },
      {
        number: 4,
        clue: 'Git',
        row: 6,
        col: 0,
        answer: 'Git',
        colour: 'bg-orange-300 text-black',
      },
      {
        number: 5,
        clue: 'R',
        row: 8,
        col: 2,
        answer: 'R',
        colour: 'bg-red-300 text-black',
      },
    ],
    down: [
      {
        number: 6,
        clue: 'Java',
        row: 0,
        col: 0,
        answer: 'Java',
        colour: 'bg-orange-300 text-black',
      },
      {
        number: 9,
        clue: 'SQL',
        row: 3,
        col: 1,
        answer: 'SQL',
        colour: 'bg-yellow-300 text-black',
      },
      {
        number: 8,
        clue: 'Linux',
        row: 4,
        col: 9,
        answer: 'Linux',
        colour: 'bg-yellow-300 text-black',
      },
    ],
    'diagonal-up': [
      {
        number: 14,
        clue: 'CSS',
        row: 4,
        col: 0,
        answer: 'CSS',
        colour: 'bg-sky-300 text-black',
      },
      {
        number: 10,
        clue: 'Figma',
        row: 7,
        col: 0,
        answer: 'Figma',
        colour: 'bg-purple-300 text-black',
      },
      {
        number: 11,
        clue: 'Docker',
        row: 6,
        col: 4,
        answer: 'Docker',
        colour: 'bg-green-300 text-black',
      },
    ],
    'diagonal-down': [
      {
        number: 12,
        clue: 'Python',
        row: 1,
        col: 4,
        answer: 'PYTHON',
        colour: 'bg-sky-300 text-black',
      },
      {
        number: 13,
        clue: 'HTML',
        row: 1,
        col: 6,
        answer: 'HTML',
        colour: 'bg-red-300 text-black',
      },
      {
        number: 7,
        clue: 'VSCode',
        row: 2,
        col: 0,
        answer: 'VSCode',
        colour: 'bg-red-300 text-black',
      },
    ],
  },
}

