export const wordSearchData = {
  grid: [
    ['J', 'A', 'V', 'A', 'S', 'C', 'R', 'I', 'P', 'T'],
    ['A', 'M', 'Q', 'D', 'P', 'S', 'H', 'Y', 'V', 'R'],
    ['V', 'L', 'S', 'A', 'O', 'Y', 'X', 'T', 'E', 'F'],
    ['A', 'S', 'R', 'E', 'A', 'C', 'T', 'K', 'M', 'H'],
    ['C', 'Q', 'C', 'M', 'M', 'D', 'C', 'H', 'G', 'L'],
    ['R', 'L', 'G', 'O', 'T', 'O', 'S', 'T', 'O', 'I'],
    ['G', 'I', 'T', 'T', 'D', 'N', 'S', 'C', 'R', 'N'],
    ['F', 'F', 'U', 'R', 'M', 'E', 'U', 'W', 'O', 'U'],
    ['C', 'W', 'I', 'N', 'D', 'O', 'W', 'S', 'J', 'X'],
  ],
  /* List the left-most row and column number for each word. 
  - Answer: The actual language/tool/OS in the grid
  - Colour: The stripe used in the background for each word.
  - Number: Layer order (used when there are overlapping words). It is the z-index.
  - Clue: The text that will appear in the word bank.
  - Category: Categorized in the word bank. Options are 'Languages', 'Tools', and 'Operating Systems'.
  */
  clues: {
    across: [
      {
        number: 1,
        clue: 'JavaScript',
        row: 0,
        col: 0,
        answer: 'JavaScript',
        colour: 'bg-yellow-300 text-black',
        category: 'Languages',
      },
      {
        number: 2,
        clue: 'C',
        row: 6,
        col: 7,
        answer: 'C',
        colour: 'bg-purple-300 text-black',
        category: 'Languages',
      },
      {
        number: 3,
        clue: 'React',
        row: 3,
        col: 2,
        answer: 'React',
        colour: 'bg-green-300 text-black',
        category: 'Tools',
      },
      {
        number: 4,
        clue: 'Git',
        row: 6,
        col: 0,
        answer: 'Git',
        colour: 'bg-orange-300 text-black',
        category: 'Tools',
      },
      {
        number: 5,
        clue: 'R',
        row: 7,
        col: 3,
        answer: 'R',
        colour: 'bg-red-300 text-black',
        category: 'Languages',
      },
      {
        number: 15,
        clue: 'Windows',
        row: 8,
        col: 1,
        answer: 'Windows',
        colour: 'bg-blue-300 text-black',
        category: 'Operating Systems',
      },
    ],
    down: [
      {
        number: 6,
        clue: 'Java',
        row: 0,
        col: 0,
        answer: 'Java',
        colour: 'bg-orange-300 text-black',
        category: 'Languages',
      },
      {
        number: 9,
        clue: 'SQL',
        row: 3,
        col: 1,
        answer: 'SQL',
        colour: 'bg-yellow-300 text-black',
        category: 'Languages',
      },
      {
        number: 8,
        clue: 'Linux',
        row: 4,
        col: 9,
        answer: 'Linux',
        colour: 'bg-yellow-300 text-black',
        category: 'Operating Systems',
      },
    ],
    'diagonal-up': [
      {
        number: 14,
        clue: 'CSS',
        row: 4,
        col: 0,
        answer: 'CSS',
        colour: 'bg-sky-300 text-black',
        category: 'Languages',
      },
      {
        number: 10,
        clue: 'Figma',
        row: 7,
        col: 0,
        answer: 'Figma',
        colour: 'bg-purple-300 text-black',
        category: 'Tools',
      },
      {
        number: 11,
        clue: 'Docker',
        row: 6,
        col: 4,
        answer: 'Docker',
        colour: 'bg-green-300 text-black',
        category: 'Tools',
      },
    ],
    'diagonal-down': [
      {
        number: 12,
        clue: 'Python',
        row: 1,
        col: 4,
        answer: 'Python',
        colour: 'bg-sky-300 text-black',
        category: 'Languages',
      },
      {
        number: 13,
        clue: 'HTML',
        row: 1,
        col: 6,
        answer: 'HTML',
        colour: 'bg-red-300 text-black',
        category: 'Languages',
      },
      {
        number: 7,
        clue: 'VSCode',
        row: 2,
        col: 0,
        answer: 'VSCode',
        colour: 'bg-red-300 text-black',
        category: 'Tools',
      },
    ],
  },
}

